/**
 * Broadvoice Bugfix Agent — Main Pipeline
 *
 * Supports GitHub and Bitbucket. Set GIT_PROVIDER=github or GIT_PROVIDER=bitbucket.
 *
 * Usage:
 *   JIRA_TICKET_ID=BUG-42 pnpm run pipeline
 *   JIRA_TICKET_ID=BUG-42 pnpm run pipeline:dry-run
 */

import { readFileSync, mkdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import 'dotenv/config';

import * as jira from '../src/integrations/jira.ts';
import * as slack from '../src/integrations/slack.ts';
import * as codefresh from '../src/integrations/codefresh.ts';
import { getGitProvider, type PR } from '../src/integrations/git-provider.ts';

// ─── Config ───────────────────────────────────────────────────────────────────

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const PROMPTS_DIR = join(ROOT, '.sandcastle', 'prompts');
const LOGS_DIR = join(ROOT, '.sandcastle', 'logs');

const TICKET_ID = process.env['JIRA_TICKET_ID'];
const DRY_RUN = process.env['DRY_RUN'] === 'true';
const GIT_PROVIDER = (process.env['GIT_PROVIDER'] ?? 'github').toLowerCase();
const FIX_MODEL = process.env['FIX_AGENT_MODEL'] ?? 'claude-opus-4-6';
const REVIEW_MODEL = process.env['REVIEW_AGENT_MODEL'] ?? 'claude-sonnet-4-6';
const MAX_FIX_ITER = Number(process.env['MAX_FIX_ITERATIONS'] ?? 3);
const MAX_REVIEW_ITER = Number(process.env['MAX_REVIEW_ITERATIONS'] ?? 2);

if (!TICKET_ID) {
  console.error('ERROR: JIRA_TICKET_ID environment variable is required.');
  console.error('Usage: JIRA_TICKET_ID=BUG-42 pnpm run pipeline');
  process.exit(1);
}

// ─── Logging ──────────────────────────────────────────────────────────────────

mkdirSync(LOGS_DIR, { recursive: true });
const logFile = join(LOGS_DIR, `run-${new Date().toISOString().replace(/[:.]/g, '-')}.log`);
const logLines: string[] = [];

function log(msg: string) {
  const line = `[${new Date().toISOString()}] ${msg}`;
  console.log(line);
  logLines.push(line);
}

function saveLog() {
  writeFileSync(logFile, logLines.join('\n'), 'utf8');
}

// ─── Mock helpers (DRY_RUN) ───────────────────────────────────────────────────

function mockTicket(): jira.JiraTicket {
  return {
    key: TICKET_ID!,
    summary: '[DRY RUN] Mock bug: tasks lost on reload',
    description: 'localStorage is not persisted when tasks are added.',
    stepsToReproduce: '1. Add a task\n2. Reload the page\n3. Task is gone',
    priority: 'High',
    labels: ['agent-ready'],
    reporter: 'rui@broadvoice.com',
    assignee: null,
  };
}

function mockPR(): PR {
  return {
    id: 999,
    number: 999,
    title: `[DRY RUN] Fix: ${TICKET_ID}`,
    url: `https://${GIT_PROVIDER}.com/dry/run/pull/999`,
    branch: `agent/fix-${TICKET_ID!.toLowerCase()}`,
  };
}

// ─── Prompt loader ────────────────────────────────────────────────────────────

function loadPrompt(name: string, vars: Record<string, string>): string {
  const raw = readFileSync(join(PROMPTS_DIR, `${name}.md`), 'utf8');
  return Object.entries(vars).reduce(
    (acc, [k, v]) => acc.replaceAll(`{{${k}}}`, v),
    raw,
  );
}

// ─── Review parser ────────────────────────────────────────────────────────────

function parseReviewOutcome(output: string): {
  outcome: 'APPROVED' | 'CHANGES_REQUESTED';
  summary: string;
  changes: string;
} {
  const outcomeMatch = output.match(/OUTCOME:\s*(APPROVED|CHANGES_REQUESTED)/i);
  const summaryMatch = output.match(/SUMMARY:\s*([\s\S]*?)(?=REQUIRED_CHANGES:|$)/i);
  const changesMatch = output.match(/REQUIRED_CHANGES:\s*([\s\S]*?)$/i);

  return {
    outcome: (outcomeMatch?.[1]?.toUpperCase() as 'APPROVED' | 'CHANGES_REQUESTED') ?? 'CHANGES_REQUESTED',
    summary: summaryMatch?.[1]?.trim() ?? output.slice(0, 300),
    changes: changesMatch?.[1]?.trim() ?? '',
  };
}

function formatReviewBody(
  ticketId: string,
  providerName: string,
  outcome: 'APPROVED' | 'CHANGES_REQUESTED',
  summary: string,
  changes: string,
): string {
  const emoji = outcome === 'APPROVED' ? '✅' : '⚠️';
  const lines = [
    `## ${emoji} Automated Code Review — \`${ticketId}\``,
    '',
    `**Outcome:** \`${outcome}\``,
    '',
    '### Summary',
    summary,
  ];

  if (changes) {
    lines.push('', '### Required Changes', changes);
  }

  lines.push(
    '',
    '---',
    `*Review generated by Broadvoice Bugfix Agent (Claude AI · ${providerName})*`,
  );
  return lines.join('\n');
}

// ─── Main pipeline ────────────────────────────────────────────────────────────

async function run() {
  log(`=== Broadvoice Bugfix Agent ===`);
  log(`Provider: ${GIT_PROVIDER}  |  Ticket: ${TICKET_ID}  |  DRY_RUN: ${DRY_RUN}`);
  log(`Fix model: ${FIX_MODEL}  |  Review model: ${REVIEW_MODEL}`);

  const git = await getGitProvider();
  log(`Git provider loaded: ${git.name}`);

  // ── Step 1: Fetch Jira ticket ─────────────────────────────────────────────
  log('\nStep 1: Fetching Jira ticket…');
  const ticket = DRY_RUN ? mockTicket() : await jira.fetchTicket(TICKET_ID!);
  log(`  → ${ticket.key}: ${ticket.summary} [${ticket.priority}]`);

  await slack.notifyPipelineStart(ticket.key, ticket.summary);

  // ── Step 2: Fix Agent ─────────────────────────────────────────────────────
  log('\nStep 2: Running Fix Agent…');

  const branchName = `agent/fix-${ticket.key.toLowerCase()}`;

  const fixPrompt = loadPrompt('fix-agent', {
    TICKET_KEY: ticket.key,
    TICKET_SUMMARY: ticket.summary,
    TICKET_DESCRIPTION: ticket.description || 'No description provided.',
    STEPS_TO_REPRODUCE: ticket.stepsToReproduce || 'No steps provided.',
    PRIORITY: ticket.priority,
    LABELS: ticket.labels.join(', ') || 'none',
    GIT_PROVIDER: git.name,
    BRANCH_NAME: branchName,
  });

  if (DRY_RUN) {
    log('  [DRY RUN] Skipping Fix Agent.');
  } else {
    const { createSandbox, claudeCode } = await import('@ai-hero/sandcastle');
    const { docker } = await import('@ai-hero/sandcastle/sandboxes/docker');

    log(`  Creating sandbox on branch "${branchName}"…`);

    await using sandbox = await createSandbox({
      branch: branchName,
      sandbox: docker(),
    });

    const fixResult = await sandbox.run({
      agent: claudeCode(FIX_MODEL, { effort: 'high' }),
      prompt: fixPrompt,
      completionSignal: '<promise>COMPLETE</promise>',
      maxIterations: MAX_FIX_ITER,
    });

    log(`  Commits: ${fixResult.commits?.map((c: { sha: string }) => c.sha.slice(0, 7)).join(', ') ?? 'none'}`);
  }

  // ── Step 3: Open Pull Request ─────────────────────────────────────────────
  log('\nStep 3: Opening Pull Request…');

  const prBody = [
    `## Auto-generated fix for \`${ticket.key}\``,
    '',
    `**Summary:** ${ticket.summary}`,
    `**Priority:** ${ticket.priority}`,
    '',
    '### Description',
    ticket.description,
    '',
    '### Steps to Reproduce',
    ticket.stepsToReproduce,
    '',
    '---',
    '*Opened automatically by the Broadvoice Bugfix Agent.*',
  ].join('\n');

  const pr: PR = DRY_RUN
    ? mockPR()
    : await git.openPullRequest(`[${ticket.key}] ${ticket.summary}`, branchName, prBody);

  log(`  PR #${pr.number} opened: ${pr.url}`);

  // Add agent label (best-effort)
  if (!DRY_RUN) {
    await git.addLabels(pr.number, ['agent-fix']).catch(() => {
      log('  (label "agent-fix" not added — label may not exist yet)');
    });
  }

  // ── Step 4: Wait for CI build ─────────────────────────────────────────────
  log('\nStep 4: Waiting for CI build…');
  const buildStatus = DRY_RUN ? 'skipped' : await codefresh.waitForBuild(branchName);
  log(`  Build status: ${buildStatus}`);

  if (buildStatus === 'failure') {
    log('  Build failed — notifying Slack and exiting.');
    await slack.notifyBuildFailed(ticket.key, pr.url);
    saveLog();
    process.exit(1);
  }

  // ── Step 5: Get PR diff ───────────────────────────────────────────────────
  log('\nStep 5: Fetching PR diff…');
  const diff = DRY_RUN
    ? '--- a/src/hooks/useTasks.ts\n+++ b/src/hooks/useTasks.ts\n@@ -1 +1 @@\n-  }, []);\n+  }, [tasks]);'
    : await git.getPRDiff(pr.number);
  log(`  Diff fetched (${diff.length} chars)`);

  // ── Step 6: Review Agent ──────────────────────────────────────────────────
  log('\nStep 6: Running Review Agent…');

  const reviewPrompt = loadPrompt('review-agent', {
    TICKET_KEY: ticket.key,
    TICKET_SUMMARY: ticket.summary,
    PR_TITLE: pr.title,
    PR_URL: pr.url,
    DIFF: diff.slice(0, 12_000),
  });

  let reviewOutput = 'OUTCOME: APPROVED\nSUMMARY: Mock review passed.\nREQUIRED_CHANGES:';

  if (!DRY_RUN) {
    const { createSandbox, claudeCode } = await import('@ai-hero/sandcastle');
    const { docker } = await import('@ai-hero/sandcastle/sandboxes/docker');

    await using sandbox = await createSandbox({
      branch: branchName,
      sandbox: docker(),
    });

    const reviewResult = await sandbox.run({
      agent: claudeCode(REVIEW_MODEL),
      prompt: reviewPrompt,
      completionSignal: '<promise>COMPLETE</promise>',
      maxIterations: MAX_REVIEW_ITER,
    });

    reviewOutput = reviewResult.output ?? '';
  }

  // ── Step 7: Post review ───────────────────────────────────────────────────
  log('\nStep 7: Posting review…');
  const { outcome, summary, changes } = parseReviewOutcome(reviewOutput);
  const reviewBody = formatReviewBody(ticket.key, git.name, outcome, summary, changes);

  if (!DRY_RUN) {
    await git.submitReview(pr.number, outcome, reviewBody);
  }

  log(`  Review posted. Outcome: ${outcome}`);

  // ── Step 8: Notify Slack ──────────────────────────────────────────────────
  log('\nStep 8: Sending Slack notification…');
  await slack.notifyPipelineComplete(ticket.key, pr.url, pr.title, outcome);

  // ── Done ──────────────────────────────────────────────────────────────────
  log('\n=== Pipeline complete ===');
  log(`  Ticket:   ${ticket.key} — ${ticket.summary}`);
  log(`  Provider: ${git.name}`);
  log(`  PR:       ${pr.url}`);
  log(`  Review:   ${outcome}`);
  log(`  Log:      ${logFile}`);

  saveLog();
}

run().catch((err) => {
  console.error('\nPipeline error:', err);
  saveLog();
  process.exit(1);
});
